image : cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
#  test gitlab 
test:
     stage: test
     parallel : 3
     script: 
         - npm install 
         - npm run cy:run
     artifacts:
         paths:
           - cypress/videos  
